# Generated by Django 5.0.6 on 2024-06-15 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=250, unique=True, verbose_name="Контактный Email"
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Тема письма")),
                (
                    "message",
                    models.TextField(blank=True, null=True, verbose_name="Тело письма"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор сообщения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cообщение",
                "verbose_name_plural": "Cообщения",
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="рассылка",
                        max_length=100,
                        verbose_name="Наименование рассылки",
                    ),
                ),
                (
                    "started",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата начала рассылки",
                    ),
                ),
                (
                    "date_next",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Следующая дата рассылки",
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Дата окончания рассылки",
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "раз в день"),
                            ("weekly", "раз в неделю"),
                            ("monthly", "раз в месяц"),
                        ],
                        default="daily",
                        max_length=50,
                        verbose_name="Периодичность рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "завершена"),
                            ("created", "создана"),
                            ("started", "запущена"),
                        ],
                        default="created",
                        max_length=50,
                        verbose_name="Статус рассылки",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Активность рассылки"
                    ),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        to="newsletter.client", verbose_name="Клиент сервиса"
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["started"],
                "permissions": [("set_is_active", "Активация рассылки")],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_mailing",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время последней попытки"
                    ),
                ),
                (
                    "mail_status",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Статус попытки",
                    ),
                ),
                (
                    "mail_response",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Ответ почтового сервера",
                    ),
                ),
                (
                    "mailing_name",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newsletter.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог",
                "verbose_name_plural": "Логи",
            },
        ),
    ]
